### ISSUE TITLE
Proposed content is not available

### ISSUE THREAD

**Issue by irshadpc** [BohdanOrlov/iOS-Developer-Roadmap#16]
Core location link is not available in the below section.
iOS Developer > Practical knowledge > Cocoa Touch > Core Location

**Comment by BohdanOrlov** [comment]
@irshadpc I've checked and it works, could you please try again?

**Comment by irshadpc** [comment]
@BohdanOrlov Seems like ok but as far as my concern is with out Badoo account no one can get in to it.

**Comment by BohdanOrlov** [comment]
@irshadpc it just on a Badoo publication on Medium, the link is available even in the incognito mode.

**Comment by irshadpc** [comment]
@BohdanOrlov Thanks for the heads-up
