### ISSUE TITLE
Coordinators, POP

### ISSUE THREAD

**Issue by piv199** [BohdanOrlov/iOS-Developer-Roadmap#2]
Design Patterns -> Coordinators ?
http://khanlou.com/2015/10/coordinators-redux/
http://khanlou.com/tag/advanced-coordinators/

Protocol Oriented Programming
https://developer.apple.com/videos/play/wwdc2015/408/

Protocol Orientation Obsessed Programming should be considered?

**Comment by BohdanOrlov** [comment]
Thank you, added!

Protocol Orientation **Obsessed** Programming is not a **topic** but an **opinion** on protocol-oriented programming, so no reason to add it ;)
