### ISSUE TITLE
Divide knowledge areas differently 

### ISSUE THREAD

**Issue by lsolniczek** [BohdanOrlov/iOS-Developer-Roadmap#26]
In my opinion, current divide is not good. `Practical knowledge` on the right side is also a `CS knowledge` and the left side topic are also very welcome to learn in practice :)

What I suggest is to divide this a little bit different: 
- Left - `General CS knowledge`
- Right - `Specific iOS development knowledge`

What do you think?

**Comment by BohdanOrlov** [comment]
hey @lsolniczek! I think you just added two words to make the names more descriptive, they merely give a bit better idea of what is inside but this comes at cost of the extra word, so I don't think it is a good idea to proceed with renaming. Thanks.
