### ISSUE TITLE
makes no chronological sense

### ISSUE THREAD

**Issue by hsavit1** [BohdanOrlov/iOS-Developer-Roadmap#27]
im looking at the [text version](https://github.com/BohdanOrlov/iOS-Developer-Roadmap/blob/master/RoadmapProject/Script/Generated/ROADMAP.md)

why, for example, would you recommend someone to learn graph theory before understanding basic data structures like stacks and queues ?

**Comment by BohdanOrlov** [comment]
I don't any point where I recommend that there are no recommendations about the order.
