### ISSUE TITLE
Roadmap project won't compile for Swift 4.1

### ISSUE THREAD

**Issue by plasticbraindotcom** [BohdanOrlov/iOS-Developer-Roadmap#34]
Trying to compile the Roadmap project fails in Xcode 9.3.1 / Swift 4.1 (macOS 10.13.4), due to outdated Yaml 3.3.1 module defined in Podfile.lock. Error:

Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1…

Attempting to resolve by updating Yaml via performing a pod update resulted in another cocoapods error (running cocoapods-1.5.3, cocoapods-rome-1.0.0):

NoMethodError - undefined method `build_settings' for nil:NilClass
/Library/Ruby/Gems/2.3.0/gems/cocoapods-rome-1.0.0/lib/cocoapods-rome/post_install.rb:44:in `block in enable_debug_information'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-rome-1.0.0/lib/cocoapods-rome/post_install.rb:42:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-rome-1.0.0/lib/cocoapods-rome/post_install.rb:42:in `enable_debug_information'
…

**Comment by BohdanOrlov** [comment]
Thank you for the report, fixed!
