### ISSUE TITLE
Module compiled with Swift 4.2 cannot be imported by the Swift 5.0.1 compiler

### ISSUE THREAD

**Issue by rainfor3st** [BohdanOrlov/iOS-Developer-Roadmap#42]

**Comment by rainfor3st** [comment]
Got this error when I'm trying to build the project.
Xcode Version 10.2.1

**Comment by Yurii201811** [comment]
Please add support for Swift 5 with Xcode 10.2 :)

**Comment by ShawnMa16** [comment]
> Got this error when I'm trying to build the project.
> Xcode Version 10.2.1

Just figured out how to deal with it.
Basically you'll need to rebuild the library through Swift 5
First install cocoapods-rome by `gem install cocoapods-rome`
Then go to folder **cocoapods-rome** and `pod install`

Then you are all good to go

**Comment by BohdanOrlov** [comment]
@rainfor3st also I've just merged swift 5 support from @dgenyk, can I close this issue now?

**Comment by rainfor3st** [comment]
@BohdanOrlov Sure, thanks a lot.
